// Source - https://stackoverflow.com/a/70412739
// Posted by t.olev
// Retrieved 2026-07-25, License - CC BY-SA 4.0

plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
}
